name: PR Verifier

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Print ENV and triggering event
        uses: hmarr/debug-action@v1.0.0

  verify:
    name: Verify PR contents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verifier action
        uses: ./.github/actions/verifier
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
